# Generated by Django 6.0.5 on 2026-06-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0002_alter_vehicle_id'),
        ('ev_data', '0003_alter_maintenancelog_id_and_more'),
    ]

    operations = [
    ]
