# Generated by Django 6.0.5 on 2026-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0004_merge_20260605_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedule',
            name='component',
            field=models.CharField(choices=[('battery', 'Battery'), ('coolant', 'Coolant'), ('gear_oil', 'Gear Oil / Transmission'), ('brake', 'Brake'), ('tyre', 'Tyre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='interval_km',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='interval_months',
            field=models.PositiveIntegerField(),
        ),
    ]
