# Generated by Django 6.0.5 on 2026-06-15 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0005_alter_serviceschedule_component_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=20)),
                ('notification_type', models.CharField(choices=[('maintenance_due', 'Maintenance Due'), ('low_health', 'Low Health')], max_length=30)),
                ('level', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('cycle_marker', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_data.vehicle')),
            ],
        ),
    ]
