# Generated by Django 6.0.5 on 2026-06-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceschedule',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='last_reset_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='cycle_marker',
            field=models.CharField(blank=True, default='legacy', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance')], max_length=30),
        ),
    ]
