# Generated by Django 6.0.5 on 2026-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0007_serviceschedule_last_reset_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='cycle_marker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
