# Generated by Django 6.0.5 on 2026-06-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0008_alter_notification_cycle_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='cycle_marker',
            field=models.CharField(max_length=100),
        ),
    ]
