# Generated by Django 6.0.5 on 2026-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0009_alter_notification_cycle_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='s_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
