# Generated by Django 6.0.5 on 2026-06-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0010_notification_s_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceschedule',
            name='status_percent',
            field=models.IntegerField(default=100),
        ),
    ]
