# Generated by Django 6.0.5 on 2026-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0011_serviceschedule_status_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_reset',
            field=models.BooleanField(default=False),
        ),
    ]
