# Generated by Django 6.0.5 on 2026-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0012_notification_is_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_checked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_checked_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
