# Generated by Django 6.0.5 on 2026-06-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0013_notification_last_checked_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_reset',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='last_checked_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='last_checked_km',
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='last_checked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='last_checked_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
