# Generated by Django 6.0.6 on 2026-06-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0014_remove_notification_is_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='service_type',
            field=models.CharField(choices=[('checking', 'Checked'), ('replacement', 'Replacement')], default='checking', max_length=20),
        ),
    ]
